### ISSUE TITLE
Changing the instanceType in an existing NodeGroup results in a 400 failure to delete the LaunchConfig since it is attached to an active ASG

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#178]
When a NodeGroup is stood up with a given instance type, e.g. `t2.medium`, and then on a future update is changed to say `t3.large`, results in the following error:

```
Diagnostics:
  aws:ec2:LaunchConfiguration (update-existing-nodegroup-ng-2-ondemand-large-nodeLaunchConfiguration):
    error: Plan apply failed: deleting urn:pulumi:dev1::update-existing-nodegroup::eks:index:NodeGroup$aws:ec2/launchConfiguration:LaunchConfiguration::update-existing-nodegroup-ng-2-ondemand-large-nodeLaunchConfiguration: 
    error deleting Autoscaling Launch Configuration (update-existing-nodegroup-ng-2-ondemand-large-nodeLaunchConfiguration-d0932eb):
    ResourceInUse: Cannot delete launch configuration update-existing-nodegroup-ng-2-ondemand-large-nodeLaunchConfiguration-d0932eb because it is attached to AutoScalingGroup update-existing-nodegroup-ng-2-ondemand-large-6410fe15-NodeGroup-1DIVWWS4FCMIU
    status code: 400, request id: f7bfd557-9505-11e9-b696-8ff9971bc5b3
```

See:
- Issue in https://github.com/terraform-providers/terraform-provider-aws/issues/8485
- TF [work-around](https://gist.github.com/Deichindianer/e4879c7f6dbc6eb6a024c5531f91483f), but does not work in `pulumi/eks` as we do not expose `namePrefix` as an opt in `aws.ec2.LaunchConfiguration`
- Changing the `name` of the LaunchConfig resulted in the same error

Manual clean up of the LaunchConfig in the state snapshot and AWS seems to be the only mitigation I've found.

cc @jen20 @lukehoban

**Comment by lukehoban** [comment]
This is a little surprising. Pulumi does create before delete by defat so a new launch configuration should have been created and the Autoscaling group should have been updated to use it prior to attempting to delete the previous launch configuration. 

Could you share a full output of an update that attempts to make this change?

**Comment by metral** [comment]
Per https://github.com/terraform-providers/terraform-provider-aws/issues/8485#issuecomment-507299533, this was fixed in https://github.com/terraform-providers/terraform-provider-aws/pull/7819 and available in 2.1.0 of tf-aws. We're currently on [2.12.0](https://github.com/pulumi/terraform-provider-aws/pull/56) but seem to be still hitting this bug.

/cc @jen20 @stack72

**Comment by lukehoban** [comment]
@metral Does this reliably repro?

**Comment by metral** [comment]
I have not been able to repro this. It could have been due to a rabbit hole I was in the middle of. Closing this out for now, and I'll re-open if necessary.

**Comment by ljani** [comment]
I'm still seeing this.

Terraform seems to have some problems as well: https://github.com/terraform-providers/terraform-provider-aws/issues/8485

**Comment by ljani** [comment]
I think I found a way to reproduce this:
- Create a "basic" EKS setup using pulumi
- Make sure your role does **not** have the permission `autoscaling:TerminateInstanceInAutoScalingGroup`
  - An explicit deny could work as well? Mine was implicit.
- Run `pulumi up` which results in cloud formation stack template change (`[diff: ~templateBody]`) and it'll fail with not having the permission
  - Mine was some change by AWS, I think a worker image update
- The second `pulumi up` will fail with `Cannot delete launch configuration ..., because it is attached to AutoScalingGroup ...` as there is a `aws:ec2:LaunchConfiguration ... completing deletion from previous update`

**Comment by zebulonj** [comment]
For what it's worth, I encounter this any time internal changes in `new eks.Cluster(...)` cause Pulumi to attempt to change the launch configuration.

**Comment by bsod90** [comment]
It seems like it's still an issue for me as well... Just like @zebulonj , I'm using `eks.Cluster` without much extra configuration. Eventually something amongst the objects it created produces a diff (an AMI id in my case), and then it's starting to fail with 
```
... ResourceInUse: Cannot delete launch configuration cubeapp-eu-central-1-2-primary-ng-nodeLaunchConfiguration-8e54547 because it is attached to AutoScalingGroup cubeapp-eu-central-1-2-primary-ng-55bb153a-NodeGroup-1I26U3PIGT5T0 ...```

What would be the best manual workaround for this? Thanks!

**Comment by oliveratprimer** [comment]
Seeing this every time I try to do a change to my EKS

**Comment by teddyknox** [comment]
Hi, any update on this? I'm having the same issue.

**Comment by viveklak** [comment]
Reopened the issue and added to triage queue for next iteration.

**Comment by tma-unwire** [comment]
I consider rewriting the pulumi_eks stuff to plain pulumi_aws to work around this. Then I will have finer control of when the launch configuration needs to be recreated - which is just about never as we use SpotInst for al that.

**Comment by ekahaa-support** [comment]
We have had this issue as well. Any updates please?

**Comment by KrisJohnstone** [comment]
Also having this issue :(

**Comment by tma-unwire** [comment]
It hyas been a long time.... any news? Is this on the backlog?

**Comment by tma-unwire** [comment]
Are there any known work-arounds, or do we have to redo the complete cluster :-(

Right now I have a launch configuration in "delete pending" state and the only solution I know of, is the export-edit-import one :-(

**Comment by benjamin658** [comment]
Same issue here, I want to adjust the `nodeSubnetIds`.

**Comment by benjamin658** [comment]
I have confirmed that the workaround @tma-unwire provided is workable, also thanks for the pulumi tech team support.

When you encounter the error, here is the step:

1. Login to the aws console, you should see the new launch configuration is already created.
2. Edit the auto scaling group, associate to the new launch config.
3. Back to the pulumi, and run `pulumi refresh`.
4. Run `pulumi up` again, you should get rid of the error.

**Comment by stack72** [comment]
@roothorp please can we try and recreate this issue so that we can isolate what we will need to fix here :)

**Comment by LucasJC** [comment]
> I have confirmed that the workaround @tma-unwire provided is workable, also thanks to the pulumi tech team support.
> 
> When you encounter the error, here is the step:
> 
>     1. Login to the aws console, you should see the new launch configuration is already created.
> 
>     2. Edit the auto scaling group, associate to the new launch config.
> 
>     3. Back to the pulumi, and run `pulumi refresh`.
> 
>     4. Run `pulumi up` again, you should get rid of the error.

I had this same issue and wanted to leave an alternative in case this is not working:
In case you dont find the new launch config created, you can create a temporal one and attach it to the asg.
This will let pulumi delete the old launch config on a pulumi up.

Afterwards dont forget to delete the temporal launch config

**Comment by kovaxur** [comment]
We have the same issue, Pulumi create the new LaunchConfiguration then tries to delete the old before replacing with the new, so it fails.

**Comment by drawnwren** [comment]
This is still failing.

**Comment by ceelian** [comment]
This also hit me, it's still an issue.
